2016-04-12 13:58:06,998 - knowledge_logger - main.py-handle-api- : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'link not like '%statuory%'' at line 1")
2016-04-12 13:58:06,999 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 131, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 193, in handle_general
    return controller.process_general_request(request, db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 54, in process_general_request
    return process_get_notifications(db, request_frame, user_id)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 203, in process_get_notifications
    notifications = db.get_notifications(request.notification_type, session_user)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 6019, in get_notifications
    aliases, join_type, join_conditions, where_condition
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 204, in get_data_from_multiple_tables
    return self.select_all(query)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 150, in select_all
    cursor.execute(query)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'link not like '%statuory%'' at line 1")

2016-04-12 13:59:00,904 - knowledge_logger - main.py-handle-api- : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'link not like '%statuory%'' at line 1")
2016-04-12 13:59:00,905 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 131, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 193, in handle_general
    return controller.process_general_request(request, db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 54, in process_general_request
    return process_get_notifications(db, request_frame, user_id)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 203, in process_get_notifications
    notifications = db.get_notifications(request.notification_type, session_user)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 6021, in get_notifications
    aliases, join_type, join_conditions, where_condition
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 206, in get_data_from_multiple_tables
    return self.select_all(query)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 150, in select_all
    cursor.execute(query)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'link not like '%statuory%'' at line 1")

2016-04-12 14:19:58,187 - knowledge_logger - main.py-handle-api- : tuple index out of range
2016-04-12 14:19:58,187 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 131, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 193, in handle_general
    return controller.process_general_request(request, db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 54, in process_general_request
    return process_get_notifications(db, request_frame, user_id)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 203, in process_get_notifications
    notifications = db.get_notifications(request.notification_type, session_user)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 6004, in get_notifications
    user_type = self.get_user_type(session_user)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 5990, in get_user_type
    user_group_id = result[0][0]
IndexError: tuple index out of range

2016-04-12 15:39:04,809 - knowledge_logger - main.py-handle-api- : tuple index out of range
2016-04-12 15:39:04,809 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 131, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 193, in handle_general
    return controller.process_general_request(request, db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 54, in process_general_request
    return process_get_notifications(db, request_frame, user_id)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 203, in process_get_notifications
    notifications = db.get_notifications(request.notification_type, session_user)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 6004, in get_notifications
    user_type = self.get_user_type(session_user)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 5990, in get_user_type
    user_group_id = result[0][0]
IndexError: tuple index out of range

2016-04-12 15:41:48,036 - knowledge_logger - main.py-handle-api- : tuple index out of range
2016-04-12 15:41:48,037 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 131, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 193, in handle_general
    return controller.process_general_request(request, db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 54, in process_general_request
    return process_get_notifications(db, request_frame, user_id)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 203, in process_get_notifications
    notifications = db.get_notifications(request.notification_type, session_user)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 6004, in get_notifications
    user_type = self.get_user_type(session_user)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 5990, in get_user_type
    user_group_id = result[0][0]
IndexError: tuple index out of range

2016-04-12 15:45:47,943 - knowledge_logger - main.py-handle-api- : tuple index out of range
2016-04-12 15:45:47,943 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 131, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 193, in handle_general
    return controller.process_general_request(request, db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 54, in process_general_request
    return process_get_notifications(db, request_frame, user_id)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 203, in process_get_notifications
    notifications = db.get_notifications(request.notification_type, session_user)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 6004, in get_notifications
    user_type = self.get_user_type(session_user)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 5990, in get_user_type
    user_group_id = result[0][0]
IndexError: tuple index out of range

2016-04-12 15:51:12,324 - knowledge_logger - main.py-handle-api- : tuple index out of range
2016-04-12 15:51:12,325 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 131, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 193, in handle_general
    return controller.process_general_request(request, db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 54, in process_general_request
    return process_get_notifications(db, request_frame, user_id)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 203, in process_get_notifications
    notifications = db.get_notifications(request.notification_type, session_user)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 6004, in get_notifications
    user_type = self.get_user_type(session_user)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 5990, in get_user_type
    user_group_id = result[0][0]
IndexError: tuple index out of range

2016-04-13 10:19:08,966 - knowledge_logger - main.py-handle-api- : tuple index out of range
2016-04-13 10:19:08,967 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/server/main.py", line 131, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/server/main.py", line 193, in handle_general
    return controller.process_general_request(request, db)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/server/controller/generalcontroller.py", line 54, in process_general_request
    return process_get_notifications(db, request_frame, user_id)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/server/controller/generalcontroller.py", line 233, in process_get_notifications
    notifications = db.get_notifications(request.notification_type, session_user)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/server/database.py", line 6180, in get_notifications
    user_type = self.get_user_type(session_user)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/server/database.py", line 6166, in get_user_type
    user_group_id = result[0][0]
IndexError: tuple index out of range

2016-04-13 10:32:53,632 - knowledge_logger - main.py-parse-request : expected key "l_id" is missing in the dictionary, but received: {u'level_name': u'l1', u'level_id': None, u'level_position': 1}
2016-04-13 10:32:53,643 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/server/main.py", line 99, in _parse_request
    data
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/knowledgemaster.py", line 974, in parse_structure
    request = parse_structure_VariantType_knowledgemaster_Request(request)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/parse_structure.py", line 108, in parse_structure_VariantType_knowledgemaster_Request
    return knowledgemaster.Request.parse_structure(data)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/knowledgemaster.py", line 63, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/knowledgemaster.py", line 93, in parse_inner_structure
    levels = parse_structure_VectorType_RecordType_core_Level(levels)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/parse_structure.py", line 1254, in parse_structure_VectorType_RecordType_core_Level
    lst.append(parse_structure_RecordType_core_Level(item))
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/parse_structure.py", line 2889, in parse_structure_RecordType_core_Level
    return core.Level.parse_structure(data)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/core.py", line 700, in parse_structure
    data = parse_dictionary(data, ["l_id", "l_position", "l_name"])
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/jsonvalidators.py", line 143, in parse_dictionary
    raise expectation_error(msg, x)
ValueError: expected key "l_id" is missing in the dictionary, but received: {u'level_name': u'l1', u'level_id': None, u'level_position': 1}

2016-04-13 10:36:44,322 - knowledge_logger - main.py-parse-request : expected key "l_position" is missing in the dictionary, but received: {u'l_id': None, u'level_name': u'l1', u'level_position': 1}
2016-04-13 10:36:44,323 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/server/main.py", line 99, in _parse_request
    data
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/knowledgemaster.py", line 974, in parse_structure
    request = parse_structure_VariantType_knowledgemaster_Request(request)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/parse_structure.py", line 108, in parse_structure_VariantType_knowledgemaster_Request
    return knowledgemaster.Request.parse_structure(data)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/knowledgemaster.py", line 63, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/knowledgemaster.py", line 93, in parse_inner_structure
    levels = parse_structure_VectorType_RecordType_core_Level(levels)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/parse_structure.py", line 1254, in parse_structure_VectorType_RecordType_core_Level
    lst.append(parse_structure_RecordType_core_Level(item))
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/parse_structure.py", line 2889, in parse_structure_RecordType_core_Level
    return core.Level.parse_structure(data)
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/core.py", line 700, in parse_structure
    data = parse_dictionary(data, ["l_id", "l_position", "l_name"])
  File "/home/solar/projects/Aparajitha-SAAS/Src-server/protocol/jsonvalidators.py", line 143, in parse_dictionary
    raise expectation_error(msg, x)
ValueError: expected key "l_position" is missing in the dictionary, but received: {u'l_id': None, u'level_name': u'l1', u'level_position': 1}

