2016-03-23 18:37:39,407 - knowledge_logger - main.py-handle-api : 'str' object has no attribute 'tzinfo'
2016-03-23 18:37:39,421 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 129, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 189, in handle_general
    return controller.process_general_request(request, db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 50, in process_general_request
    return process_get_audit_trails(db, request_frame, user_id)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 195, in process_get_audit_trails
    audit_trails = db.get_audit_trails(user_id)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 5640, in get_audit_trails
    date = self.datetime_to_string_time(row[3])
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 361, in datetime_to_string_time
    local_dt = local.localize(datetime_in_string, is_dst=None)
  File "/usr/lib/python2.7/dist-packages/pytz/tzinfo.py", line 303, in localize
    if dt.tzinfo is not None:
AttributeError: 'str' object has no attribute 'tzinfo'

2016-03-23 18:38:33,350 - knowledge_logger - main.py-handle-api : 'str' object has no attribute 'tzinfo'
2016-03-23 18:38:33,350 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 129, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 189, in handle_general
    return controller.process_general_request(request, db)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 50, in process_general_request
    return process_get_audit_trails(db, request_frame, user_id)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/controller/generalcontroller.py", line 195, in process_get_audit_trails
    audit_trails = db.get_audit_trails(user_id)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 5640, in get_audit_trails
    date = self.datetime_to_string_time(row[3])
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/database.py", line 361, in datetime_to_string_time
    local_dt = local.localize(datetime_in_string, is_dst=None)
  File "/usr/lib/python2.7/dist-packages/pytz/tzinfo.py", line 303, in localize
    if dt.tzinfo is not None:
AttributeError: 'str' object has no attribute 'tzinfo'

2016-03-23 18:41:00,360 - knowledge_logger - main.py-handle-api : expected a string, but received: datetime.datetime(2016, 3, 21, 11, 46, 31, tzinfo=<UTC>)
2016-03-23 18:41:00,360 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 134, in handle_api_request
    respond(response_data)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 124, in respond
    response_data, response
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/server/main.py", line 87, in _send_response
    data = response_data.to_structure()
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/protocol/general.py", line 297, in to_structure
    inner = self.to_inner_structure()
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/protocol/general.py", line 559, in to_inner_structure
    "audit_trail_details": to_structure_VectorType_RecordType_general_AuditTrail(self.audit_trails),
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/protocol/to_structure.py", line 52, in to_structure_VectorType_RecordType_general_AuditTrail
    lst.append(to_structure_RecordType_general_AuditTrail(item))
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/protocol/to_structure.py", line 164, in to_structure_RecordType_general_AuditTrail
    return general.AuditTrail.to_structure(data)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/protocol/general.py", line 670, in to_structure
    "date": to_structure_CustomTextType_20(self.date)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/protocol/to_structure.py", line 571, in to_structure_CustomTextType_20
    return parse_custom_string(data, 20)
  File "/home/thickpadi5/Projects/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 87, in parse_custom_string
    raise expectation_error("a string", x)
ValueError: expected a string, but received: datetime.datetime(2016, 3, 21, 11, 46, 31, tzinfo=<UTC>)

2016-03-23 18:03:52,902 - knowledge_logger - main.py-handle-api : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
2016-03-23 18:03:52,939 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 129, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 181, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/technocontroller.py", line 51, in process_techno_request
    return save_client(db, request_frame, session_user)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/technomastercontroller.py", line 277, in save_client
    result4 = db.save_unit(client_id, units_list, business_group_id, legal_entity_id, division_id, session_user)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 4290, in save_unit
    result = self.bulk_insert(self.tblUnits, columns, values_list)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 222, in bulk_insert
    return self.execute(query)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 157, in execute
    return cursor.execute(query)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")

2016-03-23 18:10:28,765 - knowledge_logger - main.py-handle-api : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
2016-03-23 18:10:28,765 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 129, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 181, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/technocontroller.py", line 51, in process_techno_request
    return save_client(db, request_frame, session_user)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/technomastercontroller.py", line 277, in save_client
    result4 = db.save_unit(client_id, units_list, business_group_id, legal_entity_id, division_id, session_user)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 4290, in save_unit
    result = self.bulk_insert(self.tblUnits, columns, values_list)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 222, in bulk_insert
    return self.execute(query)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 157, in execute
    return cursor.execute(query)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")

2016-03-23 18:11:34,146 - knowledge_logger - main.py-handle-api : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
2016-03-23 18:11:34,146 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 129, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 181, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/technocontroller.py", line 51, in process_techno_request
    return save_client(db, request_frame, session_user)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/technomastercontroller.py", line 277, in save_client
    result4 = db.save_unit(client_id, units_list, business_group_id, legal_entity_id, division_id, session_user)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 4290, in save_unit
    result = self.bulk_insert(self.tblUnits, columns, values_list)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 222, in bulk_insert
    return self.execute(query)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 157, in execute
    return cursor.execute(query)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")

2016-03-23 18:19:34,735 - knowledge_logger - main.py-handle-api : (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
2016-03-23 18:19:34,735 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 129, in handle_api_request
    response_data = unbound_method(self, request_data, self._db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 181, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/technocontroller.py", line 51, in process_techno_request
    return save_client(db, request_frame, session_user)
  File "/home/king/projects/aparajitha-saas/Src-server/server/controller/technomastercontroller.py", line 277, in save_client
    result4 = db.save_unit(client_id, units_list, business_group_id, legal_entity_id, division_id, session_user)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 4290, in save_unit
    result = self.bulk_insert(self.tblUnits, columns, values_list)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 222, in bulk_insert
    return self.execute(query)
  File "/home/king/projects/aparajitha-saas/Src-server/server/database.py", line 157, in execute
    return cursor.execute(query)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")

2016-03-23 19:01:38,012 - knowledge_logger - main.py-parse-request : expected a number, but received: u'1'
2016-03-23 19:01:38,478 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/king/projects/aparajitha-saas/Src-server/server/main.py", line 98, in _parse_request
    data
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/technomasters.py", line 1302, in parse_structure
    request = parse_structure_VariantType_technomasters_Request(request)
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/parse_structure.py", line 346, in parse_structure_VariantType_technomasters_Request
    return technomasters.Request.parse_structure(data)
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/technomasters.py", line 110, in parse_structure
    return _Request_class_map[name].parse_inner_structure(data)
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/technomasters.py", line 502, in parse_inner_structure
    country_wise_units = parse_structure_VectorType_RecordType_techno_master_COUNTRYWISEUNITS(country_wise_units)
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/parse_structure.py", line 306, in parse_structure_VectorType_RecordType_techno_master_COUNTRYWISEUNITS
    lst.append(parse_structure_RecordType_techno_master_COUNTRYWISEUNITS(item))
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/parse_structure.py", line 2146, in parse_structure_RecordType_techno_master_COUNTRYWISEUNITS
    return technomasters.COUNTRYWISEUNITS.parse_structure(data)
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/technomasters.py", line 441, in parse_structure
    units = parse_structure_VectorType_RecordType_techno_master_UNIT(units)
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/parse_structure.py", line 1475, in parse_structure_VectorType_RecordType_techno_master_UNIT
    lst.append(parse_structure_RecordType_techno_master_UNIT(item))
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/parse_structure.py", line 1946, in parse_structure_RecordType_techno_master_UNIT
    return technomasters.UNIT.parse_structure(data)
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/technomasters.py", line 400, in parse_structure
    industry_id = parse_structure_UnsignedIntegerType_32(industry_id)
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/parse_structure.py", line 289, in parse_structure_UnsignedIntegerType_32
    return parse_number(data, 0, 4294967295)
  File "/home/king/projects/aparajitha-saas/Src-server/protocol/jsonvalidators.py", line 40, in parse_number
    raise expectation_error("a number", x)
ValueError: expected a number, but received: u'1'

