2016-12-08 15:49:09,691 - knowledge_logger - main.py-handle-api- : list index out of range 

2016-12-08 15:49:09,697 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 194, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 312, in handle_general
    return controller.process_general_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\generalcontroller.py", line 129, in process_general_request
    result = process_get_messages(db, request_frame, user_id)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\generalcontroller.py", line 445, in process_get_messages
    db, request.from_count, request.page_count, session_user
  File "D:\Bogi\Project\Compfie\Src-server\server\database\general.py", line 335, in get_messages
    for row in rows[1]:
IndexError: list index out of range
 

2016-12-08 15:49:12,384 - knowledge_logger - main.py-handle-api- : list index out of range 

2016-12-08 15:49:12,384 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 194, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 312, in handle_general
    return controller.process_general_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\generalcontroller.py", line 129, in process_general_request
    result = process_get_messages(db, request_frame, user_id)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\generalcontroller.py", line 445, in process_get_messages
    db, request.from_count, request.page_count, session_user
  File "D:\Bogi\Project\Compfie\Src-server\server\database\general.py", line 335, in get_messages
    for row in rows[1]:
IndexError: list index out of range
 

2016-12-08 15:56:20,517 - knowledge_logger - main.py-handle-api- : sp_get_geography_levels- ()- 1305 (42000): PROCEDURE compfie_knowledge_new.sp_get_geography_levels does not exist 

2016-12-08 15:56:20,517 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 194, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 324, in handle_knowledge_master
    return controller.process_knowledge_master_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\knowledgemastercontroller.py", line 40, in process_knowledge_master_request
    result = process_get_geography_level(db, user_id)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\knowledgemastercontroller.py", line 355, in process_get_geography_level
    geography_levels = get_geography_levels(db)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\knowledgemaster.py", line 356, in get_geography_levels
    result = db.call_proc("sp_get_geography_levels", ())
  File "D:\Bogi\Project\Compfie\Src-server\server\dbase.py", line 782, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_get_geography_levels- ()- 1305 (42000): PROCEDURE compfie_knowledge_new.sp_get_geography_levels does not exist
 

2016-12-08 15:56:48,713 - knowledge_logger - main.py-handle-api- : sp_get_geography_levels- ()- 1305 (42000): PROCEDURE compfie_knowledge_new.sp_get_geography_levels does not exist 

2016-12-08 15:56:48,714 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 194, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 324, in handle_knowledge_master
    return controller.process_knowledge_master_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\knowledgemastercontroller.py", line 40, in process_knowledge_master_request
    result = process_get_geography_level(db, user_id)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\knowledgemastercontroller.py", line 355, in process_get_geography_level
    geography_levels = get_geography_levels(db)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\knowledgemaster.py", line 356, in get_geography_levels
    result = db.call_proc("sp_get_geography_levels", ())
  File "D:\Bogi\Project\Compfie\Src-server\server\dbase.py", line 782, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_get_geography_levels- ()- 1305 (42000): PROCEDURE compfie_knowledge_new.sp_get_geography_levels does not exist
 

2016-12-08 15:56:56,052 - knowledge_logger - main.py-handle-api- : sp_get_geography_levels- ()- 1305 (42000): PROCEDURE compfie_knowledge_new.sp_get_geography_levels does not exist 

2016-12-08 15:56:56,052 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 194, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 324, in handle_knowledge_master
    return controller.process_knowledge_master_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\knowledgemastercontroller.py", line 40, in process_knowledge_master_request
    result = process_get_geography_level(db, user_id)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\knowledgemastercontroller.py", line 355, in process_get_geography_level
    geography_levels = get_geography_levels(db)
  File "D:\Bogi\Project\Compfie\Src-server\server\database\knowledgemaster.py", line 356, in get_geography_levels
    result = db.call_proc("sp_get_geography_levels", ())
  File "D:\Bogi\Project\Compfie\Src-server\server\dbase.py", line 782, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_get_geography_levels- ()- 1305 (42000): PROCEDURE compfie_knowledge_new.sp_get_geography_levels does not exist
 

2016-12-08 16:12:25,673 - knowledge_logger - main.py-handle-api- : sp_save_geographylevel_master- [u'Test Title One', 1, 1, 1, '2016-12-08 16:12:25.670000']- 1305 (42000): PROCEDURE compfie_knowledge_new.sp_save_geographylevel_master does not exist 

2016-12-08 16:12:25,673 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 194, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 324, in handle_knowledge_master
    return controller.process_knowledge_master_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\knowledgemastercontroller.py", line 47, in process_knowledge_master_request
    result = process_save_geography_level(db, request_frame, user_id)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\knowledgemastercontroller.py", line 380, in process_save_geography_level
    db, country_id, levels, user_id
  File "D:\Bogi\Project\Compfie\Src-server\server\database\knowledgemaster.py", line 445, in save_geography_levels
    new_id = db.call_insert_proc("sp_save_geographylevel_master", values)
  File "D:\Bogi\Project\Compfie\Src-server\server\dbase.py", line 803, in call_insert_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_save_geographylevel_master- [u'Test Title One', 1, 1, 1, '2016-12-08 16:12:25.670000']- 1305 (42000): PROCEDURE compfie_knowledge_new.sp_save_geographylevel_master does not exist
 

2016-12-08 16:12:32,618 - knowledge_logger - main.py-handle-api- : sp_save_geographylevel_master- [u'Test Title One', 1, 1, 1, '2016-12-08 16:12:32.614000']- 1305 (42000): PROCEDURE compfie_knowledge_new.sp_save_geographylevel_master does not exist 

2016-12-08 16:12:32,619 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 194, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 324, in handle_knowledge_master
    return controller.process_knowledge_master_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\knowledgemastercontroller.py", line 47, in process_knowledge_master_request
    result = process_save_geography_level(db, request_frame, user_id)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\knowledgemastercontroller.py", line 380, in process_save_geography_level
    db, country_id, levels, user_id
  File "D:\Bogi\Project\Compfie\Src-server\server\database\knowledgemaster.py", line 445, in save_geography_levels
    new_id = db.call_insert_proc("sp_save_geographylevel_master", values)
  File "D:\Bogi\Project\Compfie\Src-server\server\dbase.py", line 803, in call_insert_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_save_geographylevel_master- [u'Test Title One', 1, 1, 1, '2016-12-08 16:12:32.614000']- 1305 (42000): PROCEDURE compfie_knowledge_new.sp_save_geographylevel_master does not exist
 

2016-12-08 17:20:12,085 - knowledge_logger - main.py-handle-api- : sp_get_statutory_notifications- [0, 2, 1]- 1305 (42000): PROCEDURE compfie_knowledge_new.sp_get_statutory_notifications does not exist 

2016-12-08 17:20:12,085 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 194, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 312, in handle_general
    return controller.process_general_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\generalcontroller.py", line 134, in process_general_request
    result = process_get_statutory_notifications(db, request_frame, user_id)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\generalcontroller.py", line 457, in process_get_statutory_notifications
    db, request.from_count, request.page_count, session_user
  File "D:\Bogi\Project\Compfie\Src-server\server\database\general.py", line 346, in get_statutory_notifications
    rows = db.call_proc('sp_get_statutory_notifications', args)
  File "D:\Bogi\Project\Compfie\Src-server\server\dbase.py", line 782, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_get_statutory_notifications- [0, 2, 1]- 1305 (42000): PROCEDURE compfie_knowledge_new.sp_get_statutory_notifications does not exist
 

2016-12-08 17:20:13,404 - knowledge_logger - main.py-handle-api- : list index out of range 

2016-12-08 17:20:13,404 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 194, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 312, in handle_general
    return controller.process_general_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\generalcontroller.py", line 129, in process_general_request
    result = process_get_messages(db, request_frame, user_id)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\generalcontroller.py", line 445, in process_get_messages
    db, request.from_count, request.page_count, session_user
  File "D:\Bogi\Project\Compfie\Src-server\server\database\general.py", line 335, in get_messages
    for row in rows[1]:
IndexError: list index out of range
 

2016-12-08 17:20:14,484 - knowledge_logger - main.py-handle-api- : list index out of range 

2016-12-08 17:20:14,494 - knowledge_logger - main.py : Traceback (most recent call last):
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 194, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Bogi\Project\Compfie\Src-server\server\main.py", line 312, in handle_general
    return controller.process_general_request(request, db)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\generalcontroller.py", line 129, in process_general_request
    result = process_get_messages(db, request_frame, user_id)
  File "D:\Bogi\Project\Compfie\Src-server\server\controller\generalcontroller.py", line 445, in process_get_messages
    db, request.from_count, request.page_count, session_user
  File "D:\Bogi\Project\Compfie\Src-server\server\database\general.py", line 335, in get_messages
    for row in rows[1]:
IndexError: list index out of range
 

