2018-03-03 10:31:09,917 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 10:31:12,884 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 10:39:32,986 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 10:39:32,987 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 10:47:52,993 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 10:47:52,996 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 10:56:13,000 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 10:56:13,000 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 11:04:33,006 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 11:04:33,006 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 11:12:53,012 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 11:12:53,013 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 11:21:13,019 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 11:21:13,020 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 11:29:33,026 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 11:29:33,026 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 11:35:13,128 - knowledge_error - select_one : query: SELECT t01.user_id FROM tbl_user_sessions t01  inner JOIN tbl_user_login_details t02 ON t01.user_id = t02.user_id  and is_active = 1  WHERE  session_token=%s, param:[u'adfce4fccd7640c08b40f04d0363d332'] 

2018-03-03 11:35:13,130 - knowledge_error - select_one : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 11:35:13,246 - knowledge_error - validate_rights : Traceback (most recent call last):
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\database\general.py", line 750, in validate_user_rights
    user_id = db.validate_session_token(session_token)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\dbase.py", line 640, in validate_session_token
    row = self.select_one(query, param)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\dbase.py", line 271, in select_one
    raise fetch_error()
RuntimeError: Transaction failed while processing data.
 

2018-03-03 11:35:13,246 - knowledge_error - validate_rights : Transaction failed while processing data. 

2018-03-03 11:35:13,246 - knowledge_error - handle_api_request : Transaction failed while processing data. 

2018-03-03 11:35:13,247 - knowledge_error - handle_api_request : Traceback (most recent call last):
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 272, in handle_api_request
    valid_session_data, session_user = self.validate_user_rights(request_data, _db, caller_name)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 203, in validate_user_rights
    session_user = gen.validate_user_rights(_session_db, request_data.session_token, caller_name)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\database\general.py", line 772, in validate_user_rights
    raise fetch_error()
RuntimeError: Transaction failed while processing data.
 

2018-03-03 11:35:16,098 - knowledge_error - select_one : query: SELECT t01.user_id FROM tbl_user_sessions t01  inner JOIN tbl_user_login_details t02 ON t01.user_id = t02.user_id  and is_active = 1  WHERE  session_token=%s, param:[u'adfce4fccd7640c08b40f04d0363d332'] 

2018-03-03 11:35:16,098 - knowledge_error - select_one : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 11:35:16,099 - knowledge_error - validate_rights : Traceback (most recent call last):
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\database\general.py", line 750, in validate_user_rights
    user_id = db.validate_session_token(session_token)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\dbase.py", line 640, in validate_session_token
    row = self.select_one(query, param)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\dbase.py", line 271, in select_one
    raise fetch_error()
RuntimeError: Transaction failed while processing data.
 

2018-03-03 11:35:16,099 - knowledge_error - validate_rights : Transaction failed while processing data. 

2018-03-03 11:35:16,101 - knowledge_error - handle_api_request : Transaction failed while processing data. 

2018-03-03 11:35:16,101 - knowledge_error - handle_api_request : Traceback (most recent call last):
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 272, in handle_api_request
    valid_session_data, session_user = self.validate_user_rights(request_data, _db, caller_name)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 203, in validate_user_rights
    session_user = gen.validate_user_rights(_session_db, request_data.session_token, caller_name)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\database\general.py", line 772, in validate_user_rights
    raise fetch_error()
RuntimeError: Transaction failed while processing data.
 

2018-03-03 11:35:19,546 - knowledge_error - select_one : query: SELECT t01.user_id FROM tbl_user_sessions t01  inner JOIN tbl_user_login_details t02 ON t01.user_id = t02.user_id  and is_active = 1  WHERE  session_token=%s, param:[u'adfce4fccd7640c08b40f04d0363d332'] 

2018-03-03 11:35:19,546 - knowledge_error - select_one : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 11:35:19,546 - knowledge_error - validate_rights : Traceback (most recent call last):
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\database\general.py", line 750, in validate_user_rights
    user_id = db.validate_session_token(session_token)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\dbase.py", line 640, in validate_session_token
    row = self.select_one(query, param)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\dbase.py", line 271, in select_one
    raise fetch_error()
RuntimeError: Transaction failed while processing data.
 

2018-03-03 11:35:19,546 - knowledge_error - validate_rights : Transaction failed while processing data. 

2018-03-03 11:35:19,548 - knowledge_error - handle_api_request : Transaction failed while processing data. 

2018-03-03 11:35:19,548 - knowledge_error - handle_api_request : Traceback (most recent call last):
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 272, in handle_api_request
    valid_session_data, session_user = self.validate_user_rights(request_data, _db, caller_name)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 203, in validate_user_rights
    session_user = gen.validate_user_rights(_session_db, request_data.session_token, caller_name)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\database\general.py", line 772, in validate_user_rights
    raise fetch_error()
RuntimeError: Transaction failed while processing data.
 

2018-03-03 11:35:23,790 - knowledge_error - select_one : query: SELECT t01.user_id FROM tbl_user_sessions t01  inner JOIN tbl_user_login_details t02 ON t01.user_id = t02.user_id  and is_active = 1  WHERE  session_token=%s, param:[u'adfce4fccd7640c08b40f04d0363d332'] 

2018-03-03 11:35:23,790 - knowledge_error - select_one : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 11:35:23,790 - knowledge_error - validate_rights : Traceback (most recent call last):
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\database\general.py", line 750, in validate_user_rights
    user_id = db.validate_session_token(session_token)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\dbase.py", line 640, in validate_session_token
    row = self.select_one(query, param)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\dbase.py", line 271, in select_one
    raise fetch_error()
RuntimeError: Transaction failed while processing data.
 

2018-03-03 11:35:23,792 - knowledge_error - validate_rights : Transaction failed while processing data. 

2018-03-03 11:35:23,792 - knowledge_error - handle_api_request : Transaction failed while processing data. 

2018-03-03 11:35:23,792 - knowledge_error - handle_api_request : Traceback (most recent call last):
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 272, in handle_api_request
    valid_session_data, session_user = self.validate_user_rights(request_data, _db, caller_name)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 203, in validate_user_rights
    session_user = gen.validate_user_rights(_session_db, request_data.session_token, caller_name)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\database\general.py", line 772, in validate_user_rights
    raise fetch_error()
RuntimeError: Transaction failed while processing data.
 

2018-03-03 11:37:53,043 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 11:37:53,043 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 11:46:13,046 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 11:46:13,048 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 11:54:33,052 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 11:54:33,052 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 12:02:53,058 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 12:02:53,059 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 12:10:07,865 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 12:10:07,867 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 12:11:26,200 - knowledge_error - call_proc_with_multiresult_set : procedure: sp_verify_login, param:[u'compfieadmin', '7ecfd14ba1b0d6800688a0a317a5a331'] 

2018-03-03 12:11:26,200 - knowledge_error - call_proc_with_multiresult_set : 1305 (42000): PROCEDURE compfie_knowledge_bulkupload.sp_verify_login does not exist 

2018-03-03 12:11:26,201 - knowledge_error - handle_api_request : list index out of range 

2018-03-03 12:11:26,220 - knowledge_error - handle_api_request : Traceback (most recent call last):
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 278, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 373, in handle_login
    return controller.process_login_request(request, db, self._ip_addess)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\controller\logincontroller.py", line 31, in process_login_request
    result = process_login(db, request, session_user_ip)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\controller\logincontroller.py", line 65, in process_login
    response = verify_login(db, username, encrypt_password)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\database\login.py", line 42, in verify_login
    if len(result[1]) == 0 and len(result[0]) > 0:
IndexError: list index out of range
 

2018-03-03 12:18:27,884 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 12:18:27,885 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 12:20:51,204 - knowledge_error - execute : query: delete from tbl_user_sessions where  last_accessed_time < DATE_SUB(current_ist_datetime(),INTERVAL %s MINUTE), param:[15] 

2018-03-03 12:20:51,204 - knowledge_error - execute : 1146 (42S02): Table 'compfie_knowledge_bulkupload.tbl_user_sessions' doesn't exist 

2018-03-03 12:30:39,216 - knowledge_error - call_proc_with_multiresult_set : procedure: sp_save_login_failure, param:[9, None, '2018-03-03 12:30:39.213000'] 

2018-03-03 12:30:39,216 - knowledge_error - call_proc_with_multiresult_set : 1048 (23000): Column 'ip' cannot be null 

2018-03-03 12:30:39,217 - knowledge_error - handle_api_request : list index out of range 

2018-03-03 12:30:39,220 - knowledge_error - handle_api_request : Traceback (most recent call last):
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 278, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 373, in handle_login
    return controller.process_login_request(request, db, self._ip_addess)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\controller\logincontroller.py", line 31, in process_login_request
    result = process_login(db, request, session_user_ip)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\controller\logincontroller.py", line 92, in process_login
    rows = save_login_failure(db, user_id, session_user_ip)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\database\login.py", line 235, in save_login_failure
    saved_info = result[1][0]
IndexError: list index out of range
 

2018-03-03 13:28:12,772 - knowledge_error - call_proc_with_multiresult_set : procedure: sp_save_login_failure, param:[9, None, '2018-03-03 13:28:12.764000'] 

2018-03-03 13:28:12,773 - knowledge_error - call_proc_with_multiresult_set : 1048 (23000): Column 'ip' cannot be null 

2018-03-03 13:28:12,773 - knowledge_error - handle_api_request : list index out of range 

2018-03-03 13:28:12,773 - knowledge_error - handle_api_request : Traceback (most recent call last):
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 278, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 373, in handle_login
    return controller.process_login_request(request, db, self._ip_addess)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\controller\logincontroller.py", line 31, in process_login_request
    result = process_login(db, request, session_user_ip)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\controller\logincontroller.py", line 92, in process_login
    rows = save_login_failure(db, user_id, session_user_ip)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\database\login.py", line 235, in save_login_failure
    saved_info = result[1][0]
IndexError: list index out of range
 

2018-03-03 13:52:29,420 - knowledge_error - call_proc_with_multiresult_set : procedure: sp_save_login_failure, param:[9, None, '2018-03-03 13:52:29.416000'] 

2018-03-03 13:52:29,421 - knowledge_error - call_proc_with_multiresult_set : 1048 (23000): Column 'ip' cannot be null 

2018-03-03 13:52:29,421 - knowledge_error - handle_api_request : list index out of range 

2018-03-03 13:52:29,421 - knowledge_error - handle_api_request : Traceback (most recent call last):
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 278, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\main.py", line 373, in handle_login
    return controller.process_login_request(request, db, self._ip_addess)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\controller\logincontroller.py", line 31, in process_login_request
    result = process_login(db, request, session_user_ip)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\controller\logincontroller.py", line 92, in process_login
    rows = save_login_failure(db, user_id, session_user_ip)
  File "D:\Project\Compfie Bulk Upload\Know-src-server\server\database\login.py", line 235, in save_login_failure
    saved_info = result[1][0]
IndexError: list index out of range
 

