2017-01-02 12:42:52,332 - knowledge_logger - main.py-handle-api- : object of type 'NoneType' has no len() 

2017-01-02 12:42:52,332 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 222, in handle_api_request
    return respond(response_data)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 188, in respond
    response_data, 200
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 143, in _send_response
    data = response_data.to_structure()
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/technoreports.py", line 682, in to_structure
    inner = to_structure_dictionary_values(inner)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 424, in to_structure_dictionary_values
    _module_name, _class_name, val
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 516, in to_VectorType
    to_RecordType(module_name, class_name, item)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 498, in to_RecordType
    return to_structure_dictionary_values(data)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 461, in to_structure_dictionary_values
    val = parse_values(field_name, param, val)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 268, in parse_values
    if len(val) == 0:
TypeError: object of type 'NoneType' has no len()
 

2017-01-02 13:02:51,920 - knowledge_logger - main.py-parse-request : null is not allowed 

2017-01-02 13:02:51,921 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 163, in _parse_request
    data
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/knowledgemaster.py", line 969, in parse_structure
    data = parse_dictionary(data, ["session_token", "request"])
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 381, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 282, in parse_values
    val = parse_string(val)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 79, in parse_string
    raise empty_error()
ValueError: null is not allowed
 

2017-01-02 13:02:51,921 - knowledge_logger - main.py-handle-api- : null is not allowed 

2017-01-02 13:02:51,921 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 204, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2017-01-02 13:14:31,519 - knowledge_logger - main.py-parse-request : null is not allowed 

2017-01-02 13:14:31,519 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 163, in _parse_request
    data
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/admin.py", line 1472, in parse_structure
    data = parse_dictionary(data, ["session_token", "request"])
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 381, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 282, in parse_values
    val = parse_string(val)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 79, in parse_string
    raise empty_error()
ValueError: null is not allowed
 

2017-01-02 13:14:31,520 - knowledge_logger - main.py-handle-api- : null is not allowed 

2017-01-02 13:14:31,520 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 204, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2017-01-02 13:34:09,009 - knowledge_logger - main.py-handle-api- : list index out of range 

2017-01-02 13:34:09,010 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 317, in handle_admin
    return controller.process_admin_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/admincontroller.py", line 86, in process_admin_request
    db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/admincontroller.py", line 489, in get_reassign_user_account_form_data
    groups = get_groups(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 826, in get_groups
    return return_group(groups[1])
IndexError: list index out of range
 

2017-01-02 13:34:40,495 - knowledge_logger - main.py-handle-api- : list index out of range 

2017-01-02 13:34:40,496 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 357, in handle_techno_transaction
    return controller.process_techno_transaction_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technotransactioncontroller.py", line 99, in process_techno_transaction_request
    result = process_get_groupadmingroup_unit_list(db, user_id)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technotransactioncontroller.py", line 190, in process_get_groupadmingroup_unit_list
    groupadmin_groupsList = get_groupadmin_registration_grouplist(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technotransaction.py", line 456, in get_groupadmin_registration_grouplist
    return return_groupadmin_registration_grouplist(groupadmin_grouplist)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technotransaction.py", line 460, in return_groupadmin_registration_grouplist
    for groups in groupslist[1]:
IndexError: list index out of range
 

2017-01-02 13:40:08,280 - knowledge_logger - main.py-handle-api- : list index out of range 

2017-01-02 13:40:08,280 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 333, in handle_general
    return controller.process_general_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/generalcontroller.py", line 109, in process_general_request
    result = process_get_audit_trails_filter(db, request_frame, user_id)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/generalcontroller.py", line 345, in process_get_audit_trails_filter
    audit_trail_filters = get_audit_trail_filters(db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/general.py", line 539, in get_audit_trail_filters
    countries = result[0]
IndexError: list index out of range
 

2017-01-02 13:40:42,021 - knowledge_logger - main.py-handle-api- : object of type 'NoneType' has no len() 

2017-01-02 13:40:42,021 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 222, in handle_api_request
    return respond(response_data)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 188, in respond
    response_data, 200
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 143, in _send_response
    data = response_data.to_structure()
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/technoreports.py", line 682, in to_structure
    inner = to_structure_dictionary_values(inner)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 424, in to_structure_dictionary_values
    _module_name, _class_name, val
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 516, in to_VectorType
    to_RecordType(module_name, class_name, item)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 498, in to_RecordType
    return to_structure_dictionary_values(data)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 461, in to_structure_dictionary_values
    val = parse_values(field_name, param, val)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 268, in parse_values
    if len(val) == 0:
TypeError: object of type 'NoneType' has no len()
 

2017-01-02 15:48:32,788 - knowledge_logger - main.py-handle-api- : sp_tbl_user_login_details_save- (u'867bf26fb9fa4ef3b9c984d635ae45ed', u'kmgr', '1b571bdee5975574c2edeef955f58799')- 1062 (23000): Duplicate entry '1' for key 'PRIMARY' 

2017-01-02 15:48:32,788 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 303, in handle_login
    return controller.process_login_request(request, db, self._ip_addess)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/logincontroller.py", line 64, in process_login_request
    result = process_save_logindetails(db, request)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/logincontroller.py", line 277, in process_save_logindetails
    if save_login_details(db, token, username, encrypt_password):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/login.py", line 241, in save_login_details
    (token, username, password)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 804, in call_insert_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_tbl_user_login_details_save- (u'867bf26fb9fa4ef3b9c984d635ae45ed', u'kmgr', '1b571bdee5975574c2edeef955f58799')- 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
 

2017-01-02 15:49:46,122 - knowledge_logger - main.py-handle-api- : sp_tbl_user_login_details_save- (u'867bf26fb9fa4ef3b9c984d635ae45ed', u'kmgr', '1b571bdee5975574c2edeef955f58799')- 1062 (23000): Duplicate entry '1' for key 'PRIMARY' 

2017-01-02 15:49:46,123 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 303, in handle_login
    return controller.process_login_request(request, db, self._ip_addess)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/logincontroller.py", line 64, in process_login_request
    result = process_save_logindetails(db, request)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/logincontroller.py", line 277, in process_save_logindetails
    if save_login_details(db, token, username, encrypt_password):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/login.py", line 241, in save_login_details
    (token, username, password)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 804, in call_insert_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_tbl_user_login_details_save- (u'867bf26fb9fa4ef3b9c984d635ae45ed', u'kmgr', '1b571bdee5975574c2edeef955f58799')- 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
 

2017-01-02 15:50:24,705 - knowledge_logger - main.py-handle-api- : sp_tbl_user_login_details_save- (u'867bf26fb9fa4ef3b9c984d635ae45ed', u'kmgr', '1b571bdee5975574c2edeef955f58799')- 1062 (23000): Duplicate entry '1' for key 'PRIMARY' 

2017-01-02 15:50:24,705 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 303, in handle_login
    return controller.process_login_request(request, db, self._ip_addess)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/logincontroller.py", line 64, in process_login_request
    result = process_save_logindetails(db, request)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/logincontroller.py", line 277, in process_save_logindetails
    if save_login_details(db, token, username, encrypt_password):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/login.py", line 241, in save_login_details
    (token, username, password)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 804, in call_insert_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_tbl_user_login_details_save- (u'867bf26fb9fa4ef3b9c984d635ae45ed', u'kmgr', '1b571bdee5975574c2edeef955f58799')- 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
 

2017-01-02 16:34:05,837 - knowledge_logger - main.py-parse-request : null is not allowed 

2017-01-02 16:34:05,837 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 163, in _parse_request
    data
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/knowledgetransaction.py", line 799, in parse_structure
    data = parse_dictionary(data, ["session_token", "request"])
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 381, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 282, in parse_values
    val = parse_string(val)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 79, in parse_string
    raise empty_error()
ValueError: null is not allowed
 

2017-01-02 16:34:05,838 - knowledge_logger - main.py-handle-api- : null is not allowed 

2017-01-02 16:34:05,838 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 204, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2017-01-02 18:04:07,601 - knowledge_logger - main.py-parse-request : null is not allowed 

2017-01-02 18:04:07,602 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 163, in _parse_request
    data
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/knowledgetransaction.py", line 799, in parse_structure
    data = parse_dictionary(data, ["session_token", "request"])
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 381, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 282, in parse_values
    val = parse_string(val)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 79, in parse_string
    raise empty_error()
ValueError: null is not allowed
 

2017-01-02 18:04:07,602 - knowledge_logger - main.py-handle-api- : null is not allowed 

2017-01-02 18:04:07,602 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 204, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2017-01-02 18:04:07,606 - knowledge_logger - main.py-parse-request : null is not allowed 

2017-01-02 18:04:07,606 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 163, in _parse_request
    data
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/knowledgetransaction.py", line 799, in parse_structure
    data = parse_dictionary(data, ["session_token", "request"])
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 381, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 282, in parse_values
    val = parse_string(val)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 79, in parse_string
    raise empty_error()
ValueError: null is not allowed
 

2017-01-02 18:04:07,607 - knowledge_logger - main.py-handle-api- : null is not allowed 

2017-01-02 18:04:07,607 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 204, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2017-01-02 18:04:07,611 - knowledge_logger - main.py-parse-request : null is not allowed 

2017-01-02 18:04:07,611 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 163, in _parse_request
    data
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/knowledgetransaction.py", line 799, in parse_structure
    data = parse_dictionary(data, ["session_token", "request"])
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 189, in parse_dictionary
    x = parse_dictionary_values(x, field_names, True)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 381, in parse_dictionary_values
    val = parse_values(field_name, param, val, "parse")
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 282, in parse_values
    val = parse_string(val)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/protocol/jsonvalidators.py", line 79, in parse_string
    raise empty_error()
ValueError: null is not allowed
 

2017-01-02 18:04:07,611 - knowledge_logger - main.py-handle-api- : null is not allowed 

2017-01-02 18:04:07,611 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 204, in handle_api_request
    raise ValueError(request_data)
ValueError: null is not allowed
 

2017-01-02 18:29:35,884 - knowledge_logger - main.py-handle-api- : list index out of range 

2017-01-02 18:29:35,884 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 317, in handle_admin
    return controller.process_admin_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/admincontroller.py", line 86, in process_admin_request
    db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/admincontroller.py", line 489, in get_reassign_user_account_form_data
    groups = get_groups(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 826, in get_groups
    return return_group(groups[1])
IndexError: list index out of range
 

2017-01-02 18:29:38,954 - knowledge_logger - main.py-handle-api- : sp_client_groups_approval_list- (1,)- 1054 (42S22): Unknown column 't2.is_approved' in 'where clause' 

2017-01-02 18:29:38,955 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 366, in handle_client_coordination_master
    request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/clientcoordinationmastercontroller.py", line 73, in process_client_coordination_master_request
    db, request_frame, session_user
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/clientcoordinationmastercontroller.py", line 124, in process_client_group_approval_list
    client_groups = get_client_groups_approval_list(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/clientcoordinationmaster.py", line 189, in get_client_groups_approval_list
    "sp_client_groups_approval_list", (session_user,)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 783, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_client_groups_approval_list- (1,)- 1054 (42S22): Unknown column 't2.is_approved' in 'where clause'
 

2017-01-02 18:30:04,287 - knowledge_logger - main.py-handle-api- : sp_client_groups_approval_list- (1,)- 1054 (42S22): Unknown column 't2.is_approved' in 'where clause' 

2017-01-02 18:30:04,288 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 366, in handle_client_coordination_master
    request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/clientcoordinationmastercontroller.py", line 73, in process_client_coordination_master_request
    db, request_frame, session_user
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/clientcoordinationmastercontroller.py", line 124, in process_client_group_approval_list
    client_groups = get_client_groups_approval_list(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/clientcoordinationmaster.py", line 189, in get_client_groups_approval_list
    "sp_client_groups_approval_list", (session_user,)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 783, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_client_groups_approval_list- (1,)- 1054 (42S22): Unknown column 't2.is_approved' in 'where clause'
 

2017-01-02 18:35:09,296 - knowledge_logger - main.py-handle-api- : sp_client_groups_approval_list- (1,)- 1054 (42S22): Unknown column 't2.is_approved' in 'where clause' 

2017-01-02 18:35:09,296 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 366, in handle_client_coordination_master
    request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/clientcoordinationmastercontroller.py", line 73, in process_client_coordination_master_request
    db, request_frame, session_user
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/clientcoordinationmastercontroller.py", line 124, in process_client_group_approval_list
    client_groups = get_client_groups_approval_list(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/clientcoordinationmaster.py", line 189, in get_client_groups_approval_list
    "sp_client_groups_approval_list", (session_user,)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 783, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_client_groups_approval_list- (1,)- 1054 (42S22): Unknown column 't2.is_approved' in 'where clause'
 

2017-01-02 18:35:18,903 - knowledge_logger - main.py-handle-api- : sp_client_groups_approval_list- (1,)- 1054 (42S22): Unknown column 't2.is_approved' in 'where clause' 

2017-01-02 18:35:18,903 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 366, in handle_client_coordination_master
    request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/clientcoordinationmastercontroller.py", line 73, in process_client_coordination_master_request
    db, request_frame, session_user
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/clientcoordinationmastercontroller.py", line 124, in process_client_group_approval_list
    client_groups = get_client_groups_approval_list(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/clientcoordinationmaster.py", line 189, in get_client_groups_approval_list
    "sp_client_groups_approval_list", (session_user,)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 783, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_client_groups_approval_list- (1,)- 1054 (42S22): Unknown column 't2.is_approved' in 'where clause'
 

2017-01-02 18:36:22,401 - knowledge_logger - main.py-handle-api- : sp_client_groups_approval_list- (1,)- 1054 (42S22): Unknown column 't2.is_approved' in 'where clause' 

2017-01-02 18:36:22,402 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 366, in handle_client_coordination_master
    request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/clientcoordinationmastercontroller.py", line 73, in process_client_coordination_master_request
    db, request_frame, session_user
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/clientcoordinationmastercontroller.py", line 124, in process_client_group_approval_list
    client_groups = get_client_groups_approval_list(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/clientcoordinationmaster.py", line 189, in get_client_groups_approval_list
    "sp_client_groups_approval_list", (session_user,)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 783, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_client_groups_approval_list- (1,)- 1054 (42S22): Unknown column 't2.is_approved' in 'where clause'
 

2017-01-02 19:39:40,028 - knowledge_logger - main.py-handle-api- : list index out of range 

2017-01-02 19:39:40,029 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 39, in process_techno_request
    result = get_client_groups(db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 53, in get_client_groups
    groups = get_groups(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 826, in get_groups
    return return_group(groups[1])
IndexError: list index out of range
 

2017-01-02 19:51:25,754 - knowledge_logger - main.py-handle-api- : list index out of range 

2017-01-02 19:51:25,754 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 39, in process_techno_request
    result = get_client_groups(db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 53, in get_client_groups
    groups = get_groups(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 826, in get_groups
    return return_group(groups[1])
IndexError: list index out of range
 

2017-01-02 19:52:16,414 - knowledge_logger - main.py-handle-api- : list index out of range 

2017-01-02 19:52:16,414 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 39, in process_techno_request
    result = get_client_groups(db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 53, in get_client_groups
    groups = get_groups(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 826, in get_groups
    return return_group(groups[1])
IndexError: list index out of range
 

2017-01-02 19:58:10,934 - knowledge_logger - main.py-handle-api- : list index out of range 

2017-01-02 19:58:10,934 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 39, in process_techno_request
    result = get_client_groups(db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 53, in get_client_groups
    groups = get_groups(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 826, in get_groups
    return return_group(groups[1])
IndexError: list index out of range
 

2017-01-02 20:04:12,916 - knowledge_logger - main.py-handle-api- : list index out of range 

2017-01-02 20:04:12,916 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 39, in process_techno_request
    result = get_client_groups(db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 53, in get_client_groups
    groups = get_groups(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 826, in get_groups
    return return_group(groups[1])
IndexError: list index out of range
 

2017-01-02 20:04:51,594 - knowledge_logger - main.py-handle-api- : list index out of range 

2017-01-02 20:04:51,595 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 39, in process_techno_request
    result = get_client_groups(db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 53, in get_client_groups
    groups = get_groups(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 826, in get_groups
    return return_group(groups[1])
IndexError: list index out of range
 

2017-01-02 20:04:54,385 - knowledge_logger - main.py-handle-api- : sp_assign_legal_entities_list- [7]- 1054 (42S22): Unknown column 'tle.is_approved' in 'where clause' 

2017-01-02 20:04:54,386 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 142, in process_techno_request
    db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 537, in get_assign_legal_entity_list
    assign_le_list = get_assign_legalentities(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 2046, in get_assign_legalentities
    "sp_assign_legal_entities_list", [session_user]
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 783, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_assign_legal_entities_list- [7]- 1054 (42S22): Unknown column 'tle.is_approved' in 'where clause'
 

2017-01-02 20:04:56,714 - knowledge_logger - main.py-handle-api- : list index out of range 

2017-01-02 20:04:56,715 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 39, in process_techno_request
    result = get_client_groups(db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 53, in get_client_groups
    groups = get_groups(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 826, in get_groups
    return return_group(groups[1])
IndexError: list index out of range
 

2017-01-02 20:06:20,181 - knowledge_logger - main.py-handle-api- : list index out of range 

2017-01-02 20:06:20,181 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 39, in process_techno_request
    result = get_client_groups(db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 53, in get_client_groups
    groups = get_groups(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 826, in get_groups
    return return_group(groups[1])
IndexError: list index out of range
 

2017-01-02 20:06:24,172 - knowledge_logger - main.py-handle-api- : sp_assign_legal_entities_list- [7]- 1054 (42S22): Unknown column 'tle.is_approved' in 'where clause' 

2017-01-02 20:06:24,172 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 142, in process_techno_request
    db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 537, in get_assign_legal_entity_list
    assign_le_list = get_assign_legalentities(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 2046, in get_assign_legalentities
    "sp_assign_legal_entities_list", [session_user]
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 783, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_assign_legal_entities_list- [7]- 1054 (42S22): Unknown column 'tle.is_approved' in 'where clause'
 

2017-01-02 20:08:00,608 - knowledge_logger - main.py-handle-api- : sp_assign_legal_entities_list- [7]- 1054 (42S22): Unknown column 'tle.is_approved' in 'where clause' 

2017-01-02 20:08:00,609 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 142, in process_techno_request
    db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 537, in get_assign_legal_entity_list
    assign_le_list = get_assign_legalentities(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 2046, in get_assign_legalentities
    "sp_assign_legal_entities_list", [session_user]
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 783, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_assign_legal_entities_list- [7]- 1054 (42S22): Unknown column 'tle.is_approved' in 'where clause'
 

2017-01-02 20:09:19,348 - knowledge_logger - main.py-handle-api- : sp_assign_legal_entities_list- [7]- 1054 (42S22): Unknown column 'tle.is_approved' in 'where clause' 

2017-01-02 20:09:19,349 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 142, in process_techno_request
    db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 537, in get_assign_legal_entity_list
    assign_le_list = get_assign_legalentities(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 2046, in get_assign_legalentities
    "sp_assign_legal_entities_list", [session_user]
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 783, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_assign_legal_entities_list- [7]- 1054 (42S22): Unknown column 'tle.is_approved' in 'where clause'
 

2017-01-02 20:09:45,400 - knowledge_logger - main.py-handle-api- : list index out of range 

2017-01-02 20:09:45,401 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 39, in process_techno_request
    result = get_client_groups(db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 53, in get_client_groups
    groups = get_groups(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 826, in get_groups
    return return_group(groups[1])
IndexError: list index out of range
 

2017-01-02 20:09:53,510 - knowledge_logger - main.py-handle-api- : sp_assign_legal_entities_list- [7]- 1054 (42S22): Unknown column 'tle.is_approved' in 'where clause' 

2017-01-02 20:09:53,511 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 142, in process_techno_request
    db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 537, in get_assign_legal_entity_list
    assign_le_list = get_assign_legalentities(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 2046, in get_assign_legalentities
    "sp_assign_legal_entities_list", [session_user]
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 783, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_assign_legal_entities_list- [7]- 1054 (42S22): Unknown column 'tle.is_approved' in 'where clause'
 

2017-01-02 20:16:49,963 - knowledge_logger - main.py-handle-api- : sp_assign_legal_entities_list- [7]- 1054 (42S22): Unknown column 'tle.is_approved' in 'where clause' 

2017-01-02 20:16:49,964 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 142, in process_techno_request
    db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 537, in get_assign_legal_entity_list
    assign_le_list = get_assign_legalentities(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 2046, in get_assign_legalentities
    "sp_assign_legal_entities_list", [session_user]
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 783, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_assign_legal_entities_list- [7]- 1054 (42S22): Unknown column 'tle.is_approved' in 'where clause'
 

2017-01-02 20:17:09,582 - knowledge_logger - main.py-handle-api- : sp_assign_legal_entities_list- [7]- 1054 (42S22): Unknown column 'tle.is_approved' in 'where clause' 

2017-01-02 20:17:09,583 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 142, in process_techno_request
    db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 537, in get_assign_legal_entity_list
    assign_le_list = get_assign_legalentities(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 2046, in get_assign_legalentities
    "sp_assign_legal_entities_list", [session_user]
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/dbase.py", line 783, in call_proc
    raise process_procedure_error(procedure_name, args, e)
RuntimeError: sp_assign_legal_entities_list- [7]- 1054 (42S22): Unknown column 'tle.is_approved' in 'where clause'
 

2017-01-02 20:17:12,185 - knowledge_logger - main.py-handle-api- : list index out of range 

2017-01-02 20:17:12,185 - knowledge_logger - main.py : Traceback (most recent call last):
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 210, in handle_api_request
    response_data = unbound_method(self, request_data, _db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/main.py", line 325, in handle_techno
    return controller.process_techno_request(request, db)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technocontroller.py", line 39, in process_techno_request
    result = get_client_groups(db, request_frame, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/controller/technomastercontroller.py", line 53, in get_client_groups
    groups = get_groups(db, session_user)
  File "/home/thickpadi5/Project-msft/compfie/Know-src-server/server/database/technomaster.py", line 826, in get_groups
    return return_group(groups[1])
IndexError: list index out of range
 

